# Generated by Django 4.2 on 2023-04-15 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, unique=True, verbose_name='Дата')),
                ('all_meters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Всего строящегося жилья в метрах, млн кв м')),
                ('open_meters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с открытыми продажами, млн кв м')),
                ('close_meters', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с закрытыми продажами, млн кв м')),
                ('all_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Всего строящегося жилья в метрах, %')),
                ('open_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с открытыми продажами, %')),
                ('close_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с закрытыми продажами, %')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Дата',
                'ordering': ['date'],
            },
        ),
    ]
