# Generated by Django 4.2 on 2023-04-15 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='pending_meters',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с неоткрытими продажами, млн кв м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='pending_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Жилье с неоткрытими продажами, %'),
            preserve_default=False,
        ),
    ]
