# Generated by Django 4.2 on 2023-04-16 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_flat_pending_meters_flat_pending_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150, unique=True, verbose_name='Регион')),
                ('year_2020', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Количесвто многоквартирных домов в 2020 году, шт')),
                ('year_2021', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Количесвто многоквартирных домов в 2021 году, шт')),
                ('year_2022', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Количесвто многоквартирных домов в 2022 году, шт')),
                ('year_2023', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Количесвто многоквартирных домов в 2023 году, шт')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
                'ordering': ['region'],
            },
        ),
    ]
