# Generated by Django 4.2 on 2023-04-16 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='all',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение 0')], verbose_name='Количесвто многоквартирных домов pf 2020-2023u, шт'),
            preserve_default=False,
        ),
    ]
